### ISSUE TITLE
Refactor: Enhance Database Schema to Track Agent Actions and Detailed State Information

### ISSUE THREAD

**Issue by csmangum** [Dooders/Experiments#38]
We need to expand our simulation database to capture more detailed information about agent actions, states, and interactions to enable richer analysis of agent behavior and simulation outcomes.

### Current Limitations

1. Limited action tracking:

```1:42:database.py
import logging
import sqlite3
from typing import Dict, List, Tuple

import pandas as pd

logger = logging.getLogger(__name__)


class SimulationDatabase:
    def __init__(self, db_path: str):
        """Initialize database connection and create tables if they don't exist."""
        self.conn = sqlite3.connect(db_path)
        self.cursor = self.conn.cursor()
        self._create_tables()

    def _create_tables(self):
        """Create database tables if they don't exist."""
        self.cursor.executescript(
            """
            CREATE TABLE IF NOT EXISTS Agents (
                agent_id INTEGER PRIMARY KEY,
                birth_time INTEGER,
                death_time INTEGER,
                agent_type TEXT,
                initial_position TEXT,
                initial_resources REAL
            );

            CREATE TABLE IF NOT EXISTS AgentStates (
                step_number INTEGER,
                agent_id INTEGER,
                position_x REAL,
                position_y REAL,
                resource_level REAL,
                FOREIGN KEY(agent_id) REFERENCES Agents(agent_id)
            );

            CREATE TABLE IF NOT EXISTS ResourceStates (
                step_number INTEGER,
                resource_id INTEGER,
                amount REAL,
```

The current schema only tracks basic agent and resource states without capturing individual actions or their outcomes.

2. Missing behavioral data:

```255:263:actions/share.py
    # Store experience for learning
    next_state = _get_share_state(agent)
    agent.share_module.store_experience(
        state=torch.FloatTensor(state).to(agent.share_module.device),
        action=action,
        reward=reward,
        next_state=torch.FloatTensor(next_state).to(agent.share_module.device),
        done=False,
    )
```

```181:188:actions/attack.py
    next_state = agent.get_state()
    agent.attack_module.store_experience(
        state.to_tensor(agent.attack_module.device),
        action,
        reward,
        next_state.to_tensor(agent.attack_module.device),
        not target.alive,
    )
```

Actions store valuable experience data that's currently lost after training.

### Proposed Changes

1. Add new tables to track:
   - Individual agent actions and their outcomes
   - Learning experiences and rewards
   - Combat interactions
   - Resource sharing events
   - Movement patterns

2. Schema additions:

```sql
-- Track individual agent actions
CREATE TABLE AgentActions (
    action_id INTEGER PRIMARY KEY,
    step_number INTEGER,
    agent_id INTEGER,
    action_type TEXT,
    action_target_id INTEGER,  -- For attacks/sharing
    position_before TEXT,
    position_after TEXT,
    resources_before REAL,
    resources_after REAL,
    reward REAL,
    FOREIGN KEY(agent_id) REFERENCES Agents(agent_id)
);

-- Track combat interactions
CREATE TABLE CombatEvents (
    combat_id INTEGER PRIMARY KEY,
    step_number INTEGER,
    attacker_id INTEGER,
    defender_id INTEGER,
    damage_dealt REAL,
    defender_health_before REAL,
    defender_health_after REAL,
    defender_died BOOLEAN,
    FOREIGN KEY(attacker_id) REFERENCES Agents(agent_id),
    FOREIGN KEY(defender_id) REFERENCES Agents(agent_id)
);

-- Track resource sharing
CREATE TABLE SharingEvents (
    share_id INTEGER PRIMARY KEY,
    step_number INTEGER,
    giver_id INTEGER,
    receiver_id INTEGER,
    amount_shared REAL,
    giver_resources_before REAL,
    receiver_resources_before REAL,
    cooperation_score REAL,
    FOREIGN KEY(giver_id) REFERENCES Agents(agent_id),
    FOREIGN KEY(receiver_id) REFERENCES Agents(agent_id)
);

-- Track learning experiences
CREATE TABLE LearningExperiences (
    experience_id INTEGER PRIMARY KEY,
    step_number INTEGER,
    agent_id INTEGER,
    module_type TEXT,
    state_before TEXT,
    action_taken INTEGER,
    reward REAL,
    state_after TEXT,
    loss REAL,
    FOREIGN KEY(agent_id) REFERENCES Agents(agent_id)
);
```

3. Implementation requirements:
   - Update database.py to include methods for logging these new event types
   - Modify action modules to call appropriate logging methods
   - Add methods for analyzing and exporting the new data
   - Update visualization tools to leverage new data points

### Benefits

1. Enhanced analysis capabilities:
   - Track individual agent decision-making patterns
   - Analyze combat effectiveness and strategy evolution
   - Study resource sharing networks and cooperation patterns
   - Monitor learning progress and adaptation

2. Improved debugging:
   - Better visibility into agent behavior
   - Easier identification of unexpected patterns
   - More detailed performance metrics

3. Research value:
   - Rich dataset for studying emergent behaviors
   - Detailed metrics for comparing agent types
   - Better understanding of learning effectiveness

### Implementation Notes

1. Database updates:

```44:85:database.py
                position_y REAL
            );

            CREATE TABLE IF NOT EXISTS SimulationSteps (
                step_number INTEGER PRIMARY KEY,
                total_agents INTEGER,
                system_agents INTEGER,
                independent_agents INTEGER,
                control_agents INTEGER,
                total_resources REAL,
                average_agent_resources REAL
            );
        """
        )
        self.conn.commit()

    def log_agent(
        self,
        agent_id: int,
        birth_time: int,
        agent_type: str,
        position: Tuple[float, float],
        initial_resources: float,
    ):
        """Log new agent creation."""
        self.cursor.execute(
            """
            INSERT INTO Agents (
                agent_id, birth_time, agent_type, initial_position, initial_resources
            ) VALUES (?, ?, ?, ?, ?)
        """,
            (agent_id, birth_time, agent_type, str(position), initial_resources),
        )
        self.conn.commit()

    def update_agent_death(self, agent_id: int, death_time: int):
        """Record agent death time."""
        self.cursor.execute(
            """
            UPDATE Agents 
            SET death_time = ? 
            WHERE agent_id = ?
```

Extend the existing table creation logic to include new schemas.

2. Agent modifications:

```195:220:agents/base_agent.py
        
        This method handles the core action loop including:
        1. Resource consumption and starvation checks
        2. State observation
        3. Action selection and execution
        4. State/action memory for learning
        
        The agent will not act if it's not alive. Each turn consumes base resources
        and can potentially lead to death if resources are depleted.
        """
        if not self.alive:
            return

        # Reset defense status at start of turn
        self.is_defending = False

        initial_resources = self.resource_level
        self.resource_level -= self.config.base_consumption_rate

        if self.resource_level <= 0:
            self.starvation_threshold += 1
            if self.starvation_threshold >= self.max_starvation:
                self.die()
                return
        else:
            self.starvation_threshold = 0
```

Update action handling to include database logging.

3. Consider performance implications:
   - Batch inserts for better performance
   - Index key columns for query optimization
   - Regular cleanup of old data
   - Compression strategies for large datasets

### Tasks

- [ ] Implement new database schema
- [ ] Create logging methods for each new table
- [ ] Update action modules to log events
- [ ] Add analysis methods for new data
- [ ] Update visualization tools
- [ ] Add data export functionality
- [ ] Write migration script for existing databases
- [ ] Add documentation for new features
- [ ] Create example queries and analysis scripts
